### ISSUE TITLE
Epic: Favorites

### ISSUE THREAD

**Issue by allieIsOkay** [plapicola/express-sweater-weather#20]
Workflow for favorites endpoints

- [x] User adding favorites
- [x] User favorites with bad credentials
- [x] User retrieves favorites 
- [x] User retrieves favorites with bad credentials
- [x] User can remove favorites
- [x] User removes favorites with bad credentials
