### ISSUE TITLE
Epic: User Account Creation

### ISSUE THREAD

**Issue by allieIsOkay** [plapicola/express-sweater-weather#7]
Workflow for creating user accounts

- [x] User Model
- [x] User Password Hashing
- [x] User Password Confirmation
- [x] User Account Creation
- [x] Invalid User Creation
